### ISSUE TITLE
Ram dmg bug

### ISSUE THREAD

**Issue by Derpim** [maphe/maphe.github.io#115] opened 2021-08-11 19:30 UTC
I've been trying to test ram's dmg on free gear and pushing my luck as much as possible, but it seems there is a coding error on your end, I presume as the calculator shows 95k dmg while in application its 88k. I've attached the screenshots of the run and stats on my ram. please check and see if there's any errors on the modifiers and such or if I'm Missing something. 

![IMG_20210812_002915](https://user-images.githubusercontent.com/88799303/129091182-27d4387f-0d9a-4a45-9e7c-54d4a2b2bde6.jpg)
![25](https://user-images.githubusercontent.com/88799303/129091188-349cd555-2f3b-4b12-8200-d05741a1cd17.JPG)
![IMG_20210812_000107](https://user-images.githubusercontent.com/88799303/129091190-c54c3333-bef1-4b71-b546-c98b3f6964bc.jpg)
![IMG_20210811_235432](https://user-images.githubusercontent.com/88799303/129091344-5452a4e0-1867-4ac4-a509-c17cc62df379.jpg)

**Comment by maphe** [comment] 2021-08-15 18:16
Duplicate of #117

**Closed by maphe** 2021-08-15 18:16 UTC
Labels: duplicate
